### ISSUE TITLE
Translate into JSONSchema

### ISSUE THREAD

**Issue by KOLANICH** [hcho3/xgboost-json-schema#1]
https://tools.ietf.org/html/draft-handrews-json-schema-01
https://www.jsonschema.net/
https://github.com/cloudflare/json-schema-tools

**Comment by hcho3** [comment]
Will get to this soon

**Comment by hcho3** [comment]
@KOLANICH In #6, I added a JSON schema: https://github.com/hcho3/xgboost-json-schema/pull/6/files#diff-12cac07f13656c08ae43449bcb20f402

**Comment by KOLANICH** [comment]
Thanks. Docstrings can be put into the schema using `description` too.
