### ISSUE TITLE
Missing `LearnerModelParam`

### ISSUE THREAD

**Issue by trivialfis** [hcho3/xgboost-json-schema#9]
I will try to update this along with a draft implementation if time allows.  I still insist that we should not rely on `dmlc::JSON`.

**Comment by hcho3** [comment]
> I still insist that we should not rely on dmlc::JSON

Would you like to roll your own JSON instead, or should we use a 3rd party JSON lib?

**Comment by trivialfis** [comment]
@hcho3 For now I'm copying my own JSON implementation : https://github.com/trivialfis/nih/blob/master/include/nih/json.hh Again I'm trying to avoid git submodule. ;-)

It's simple but not performative,  I will do some benchmark after we have a draft implementation.  I have seen some optimized version like: https://github.com/lemire/simdjson , we can apply some of the techniques from there after initial commit.  Techniques from simdjson seems applicable to GPU if we can put more thoughts.  But that will be a future work.

**Comment by hcho3** [comment]
@trivialfis Got it, I trust you to furnish a functional JSON implementation. Provided that it is not too complex, I would prefer your JSON implementation to 3rd-party lib.

When you have a chance, can you describe the benefits of NIH (your JSON) compared to `dmlc::JSON`? If it's quite good, maybe NIH should be merged into dmlc-core (in the long term)?

**Comment by trivialfis** [comment]
> When you have a chance, can you describe the benefits of NIH (your JSON) compared to dmlc::JSON? 

The `dmlc::JSON` is consisted of a writer and a reader, without an explicit tree like data structure (that JSON employs, or DOM).  If we were to traversal XGBoost when doing serialization,  such design makes it very difficult.  Try adding a nested json object.

Other JSON implementation has complete interface for manipulating json objects, like adding arbitrary depth of nested objects with any types as values, which can not be easily done with `dmlc::JSON`.  The completeness can make the code much cleaner and manageable, at the very least for our initial implementation.  But it was also noted  by @tqchen  that we should try to avoid 3 party implementation because relying on external library has its cost.  

So that leads to the current decision, to make it simple, clean and avoid 3 party libraries at the same time,  I copied my own implementation, and seek chance to improve the performance.

**Comment by hcho3** [comment]
@trivialfis Got it, so we want NIH to be a small, efficient JSON lib that supports nested JSON objects. I support your effort. Go for it!

**Comment by trivialfis** [comment]
Thanks.

**Comment by hcho3** [comment]
For now, we can merge NIH into XGBoost. And later let's discuss whether it should be adopted into dmlc-core.

**Comment by trivialfis** [comment]
Got it.  Will first try to do some optimizations.
